"use client";
import {useState} from "react";import Link from "next/link";import {ArrowDown,ArrowUpRight,Plus,ArrowUp} from "lucide-react";
const categories=["ALL","BRAND","INTERIOR","REAL ESTATE","FITNESS"];
const works=[["01","LUMINOUS DESIGN","INTERIOR","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=85"],["02","THE ADDRESS","REAL ESTATE","https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=85"],["03","PULLMAD","FITNESS","https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1400&q=85"],["04","UL PROJECT","BRAND","https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=85"]];
const services=[["01","WEB DESIGN","브랜드의 첫인상을 만드는 UI/UX"],["02","DEVELOPMENT","빠르고 안정적인 반응형 웹 개발"],["03","RESPONSIVE","PC부터 모바일까지 하나의 경험으로"],["04","MAINTENANCE","오픈 이후에도 지속되는 관리"]];
const faqs=["제작 기간은 얼마나 걸리나요?","수정은 몇 번까지 가능한가요?","모바일도 함께 제작되나요?","제작 후 직접 관리할 수 있나요?","도메인과 소스코드도 전달받을 수 있나요?"];
export default function Home(){const[open,setOpen]=useState<number|null>(null);const[category,setCategory]=useState("ALL");const filteredWorks=category==="ALL"?works:works.filter(w=>w[2]===category);return <main>
<header><Link href="/" className="logo">UL<span>·</span>DESIGN</Link><nav><a href="#works">WORKS</a><a href="#service">SERVICES</a><a href="#process">PROCESS</a><a href="#faq">FAQ</a></nav><a className="contact" href="#contact">PROJECT INQUIRY <ArrowUpRight size={15}/></a></header>
<section className="hero"><div className="hero-img"/><div className="hero-copy"><p className="eyebrow">WEB DESIGN / UI·UX / DEVELOPMENT</p><h1>WE DESIGN<br/><i>DIGITAL</i><br/>EXPERIENCES.</h1><p className="lead">비즈니스의 목적을 이해하고<br/>방문자와 브랜드를 연결하는 웹사이트를 만듭니다.</p></div><a className="scroll" href="#intro"><ArrowDown size={15}/> SCROLL TO EXPLORE</a></section>
<section id="intro" className="intro"><p className="eyebrow">UL DESIGN / ABOUT</p><div><h2>디자인은 보기 좋은 것을 넘어<br/><em>비즈니스의 흐름</em>을 만들어야 합니다.</h2><p>브랜드의 성격부터 고객이 문의하기까지의 경험을 설계합니다. 목적에 맞는 구조, 명확한 콘텐츠, 세련된 비주얼을 하나의 웹사이트에 담습니다.</p></div></section>
<section className="stats"><div><strong>48H</strong><span>FIRST DRAFT</span></div><div><strong>PC + MO</strong><span>RESPONSIVE</span></div><div><strong>∞</strong><span>REVISION</span></div><div><strong>01 MO</strong><span>FREE MAINTENANCE</span></div></section>
<section id="works" className="works"><div className="section-head"><div><p className="eyebrow">SELECTED WORKS</p><h2>Selected<br/><em>Projects.</em></h2></div><p>브랜드와 업종에 따라 다른 목적을 가진<br/>프로젝트를 이미지 중심으로 소개합니다.</p></div><div className="category-filter" aria-label="포트폴리오 카테고리">{categories.map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="work-grid">{filteredWorks.map((w,i)=><article className={i%3===1?"tall":""} key={w[0]}><Link href={"/portfolio/"+w[1].toLowerCase().replaceAll(" ","-")}><div className="work-image" style={{backgroundImage:"url("+w[3]+")"}}/><div className="work-meta"><div><small>{w[0]}</small><h3>{w[1]}</h3></div><span>{w[2]}</span><ArrowUpRight size={17}/></div></Link></article>)}</div></section>
<section id="service" className="service"><div className="section-head"><div><p className="eyebrow">WHAT WE DO</p><h2>Built for<br/><em>Business.</em></h2></div></div><div className="service-list">{services.map(s=><div className="service-row" key={s[0]}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p><ArrowUpRight/></div>)}</div></section>
<section id="process" className="process"><p className="eyebrow">HOW WE WORK</p><h2>A clear process.<br/><em>Better results.</em></h2><div className="process-grid">{["CONSULTATION","PLANNING","DESIGN","DEVELOPMENT","FINAL","MAINTENANCE"].map((x,i)=><div key={x}><span>0{i+1}</span><h3>{x}</h3><p>{["상담 및 요구사항 확인","사이트 구조와 콘텐츠 기획","PC / Mobile 디자인","반응형 웹사이트 개발","검수 및 최종 전달","1개월 무료 유지보수"][i]}</p></div>)}</div></section>
<section id="faq" className="faq"><div><p className="eyebrow">FAQ</p><h2>Frequently<br/><em>Asked.</em></h2></div><div>{faqs.map((q,i)=><button className="faq-row" onClick={()=>setOpen(open===i?null:i)} key={q}><span>{q}</span>{open===i?<ArrowUp/>:<Plus/>}{open===i&&<p>프로젝트의 규모와 필요한 기능에 따라 상담 후 정확한 범위와 일정을 안내드립니다. 기본 제작에는 반응형 디자인과 개발, 수정 반영, 최종 전달이 포함됩니다.</p>}</button>)}</div></section>
<section id="contact" className="cta"><p className="eyebrow">START A PROJECT</p><h2>YOUR NEXT WEBSITE<br/><em>STARTS HERE.</em></h2><a href="mailto:hello@uldesign.kr">PROJECT INQUIRY <ArrowUpRight/></a></section>
<footer><span>UL·DESIGN</span><span>WEB / UI·UX / DEVELOPMENT</span><span>© 2026 UL DESIGN</span></footer>
</main>}